name: Déploiement FTP vers OVH

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
    - name: Récupération du dépôt
      uses: actions/checkout@v2

    - name: Déploiement FTP
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./wp-content/themes/hello-child  # ou ./wp-content/themes/hello-child si tu veux pousser un dossier précis
        server-dir: /www/wp-content/themes/hello-child/