name: Upload via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Déploiement FTP
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du dépôt
        uses: actions/checkout@v2

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: wp-content/themes/hello-child/ # ✅ avec le slash final
          server-dir: www/wp-content/themes/hello-child/ # ou l’endroit exact selon OVH